### ISSUE TITLE
Dynamics Defaults Values aren't working 

### ISSUE THREAD

**Issue by gustavorodarte** [talyssonoc/structure#85]
Hy guys, 

I try to set a dynamic default value, but I received de an exception with telling me the instance method is not defined. And when I logged the instance and only showed the attributes and not methods. I try do same example present in docs but isn`t not working.

The docs example with a console.log

``` js

const User = attributes({
  name: {
    type: String,
    default: 'Anonymous' // static default value
  },
  greeting: {
    type: String,
    default: (instance) => {
      console.log("instance ------->", instance);
      instance.greeting();
    }, // dynamic default value
  },
})(class User {
  greeting() {
    return `Hello ${this.name}`;
  }
});

```
The result: 
```
instance -------> User { [Symbol(attributes)]: { name: 'Anonymous' } }
TypeError: instance.greeting is not a function
    at Object.default (/Users/rodarte/Frente/EXCHANGE/src/domain/remmitanceExchangeRate/RemmitanceExchangeRate.js:81:16)
    at derivedInitialization (/Users/rodarte/Frente/EXCHANGE/node_modules/structure/src/initialization/initializationOrder.js:12:32)
    at initializedValue (/Users/rodarte/Frente/EXCHANGE/node_modules/structure/src/initialization/initialization.js:9:10)
    at Object.initialize (/Users/rodarte/Frente/EXCHANGE/node_modules/structure/src/initialization/initialization.js:24:30)
    at Object.initialize (/Users/rodarte/Frente/EXCHANGE/node_modules/structure/src/initialization/initialize.js:4:22)
    at Object.construct (/Users/rodarte/Frente/EXCHANGE/node_modules/structure/src/attributes/decorator.js:25:24)
```

I testing in node 10.3.0 and in node 8.9.4 and produces the same result, and running the last version of structure 1.3.2

**Comment by talyssonoc** [comment]
@gustavorodarte it happens because the name of the attribute and the method are both `attributes`. Sorry for the confusion on the docs, we're gonna fix it
